[package]
name = "frb_charming"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib", "staticlib"]

[dependencies]
anyhow = "1"
chart_core = { path = "../chart_core" } 
flutter_rust_bridge = "=2.5.1"