// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.5.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

Future<Uint8List?> newLineChart(
        {required String title, required LineChartData data}) =>
    RustLib.instance.api
        .crateApiLineChartNewLineChart(title: title, data: data);

// Rust type: RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<LineChartData>>
abstract class LineChartData implements RustOpaqueInterface {}
